import Footer from '../components/Footer';
import Header from '../components/Header';
import './globals.css';
import { Roboto } from 'next/font/google';

const inter = Roboto({ subsets: ['latin'], weight: '700' });

export const metadata = {
	title: 'poultry',
	description: 'Generated by create next app',
	icons: {
		icon: '/image/logo.png',
	},
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body
				className={`bg-gradient-to-r  relative ${inter.className} custom-scroll overflow-x-hidden bg-primary dark:bg-darkprimary `}>
				<div className='sticky top-0 '>
					<Header />
				</div>
				{children}
				<Footer />
			</body>
		</html>
	);
}
